<?php
/**
 * @file
 * Code for the Popup Survey feature.
 */

/**
 * Shows this popup on every page except the listed pages.
 */
define('POPUP_VISIBILITY_NOTLISTED', 0);

/**
 * Shows this block on only the listed pages.
 */
define('POPUP_VISIBILITY_LISTED', 1);

/**
 *  Perform basic input validation
 */
function _popup_survey_admin_settings_validate($form, $form_state) {
  $ua = $form_state['values']['popup_survey_ua_exclude'];
  if( strlen($ua) > 0 && (substr($ua,0,1) == '|' || substr($ua,strlen($ua)-1,1)=='|') ) {
    form_set_error('popup_survey_ua_exclude', t('Value cannot start or end with a pipe (|) delimiter'));
  }
}


/**
 * Implements hook_page_build().
 */
function popup_survey_page_bottom(array &$page_bottom) {
  // Performance: Skip this entirely for AJAX requests.
  if (\Drupal::request()->isXmlHttpRequest()) {
    return;
  }

  // Skip this if the visitor is logged in or determined to be a crawler.
  $current_user = \Drupal::currentUser();
  if (FALSE and $current_user->isAuthenticated()) {
    return;
  }

  $config = \Drupal::configFactory()->get('popup_survey.settings');
  // Skip this if the bean to display is not set.
  $popup_config_entity_id = $config->get('popup_survey_config_entity');
  if ($popup_config_entity_id != FALSE) {
    // Randomly skip so that not all users see the popup.
    $frequency = $config->get('popup_survey_frequency') ?: 1;
    if( mt_rand(1, $frequency) === 1 ) {

      // Limited visibility popups must list at least one page.
      $visibility = $config->get('popup_survey_visibility_options');
      $visibility_pages = $config->get('popup_survey_visibility_options_pages') ?: '';

      if ($visibility === POPUP_VISIBILITY_LISTED && $visibility_pages == '') {
        return;
      }

      if( $visibility_pages ) {
        $pages = strtolower($visibility_pages);
        //$path = strtolower(drupal_get_path_alias($_GET['q']));
        $path = strtolower(\Drupal::service('path.current')->getPath());
        //$page_match = drupal_match_path($path, $pages);
        $page_match = \Drupal::service('path.matcher')->matchPath($path, $pages);
        dpm($pages);
        dpm($path);
        dpm($page_match);
        /*
        if ($path != $_GET['q']) {
          $page_match = $page_match || drupal_match_path($_GET['q'], $pages);
        }
        */

        $page_match = !($visibility xor $page_match);

        if (!$page_match) { return; }
      }

      //$path = drupal_get_path('module', 'popup_survey');

      $ua = \Drupal\Component\Utility\Html::escape($config->get('popup_survey_ua_exclude') ?: '');
      $page_bottom['popup_survey'] = [
        '#theme' => 'popup_survey',
        '#attached' => [
          'library' => [
            'popup_survey/popup_survey',
          ],
          'drupalSettings' => [
            'popup_survey' => [
              'botlist' => $ua,
            ],
          ],
        ],
      ];
      $options = ['every_page' => TRUE];
      /*
      $page['page_bottom']['popup_survey'] = ['#attached' => [] ];
      $attached = &$page['page_bottom']['popup_survey']['#attached'];

      drupal_add_js(['POPUP_SURVEY' => ['botlist' => $ua]], ['type' => 'setting']);

      $attached['css'][$path . '/css/popup_survey.css'] = $options;
      $attached['js'][$path . '/js/popup_survey.js'] = $options;
      $bean = entity_view('bean', entity_load('bean', [$bid]));
      $page['page_bottom']['popup_survey']['#markup'] = '<div class="popup-greyout">' . render($bean) . '</div>';
      */

      // DEBUG: dpm($page['page_bottom']['popup_survey']);
    }
  }
}

/**
 * Implements hook_theme().
 */
function popup_survey_theme($existing, $type, $theme, $path) {
  return [
    'popup_survey' => [
      'variables' => [
        'cancel_link_title' => 'cancel',
        'popup_body' => 'Body',
        'survey_link_url' => '',
        'survey_link_title' => 'Survey Link Title',
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_entity().
 * @param array $var a keyed array with the entity data and meta data.
 */
function _popup_survey_preprocess_entity(&$var) {
  if ($var['entity_type'] == 'popup_survey')
  {
    $url = $var['content']['field_survey_link'][0]['#markup'];
    $title = $var['content']['field_survey_link_title'][0]['#markup'];
    $reject = $var['content']['field_cancel_link_title'][0]['#markup'];
    // Turn the Survey Link and Survey Link Title fields into one anchor tag.
    $var['content']['field_survey_link'][0]['#markup'] = '<a href="' . $url . '" target="_blank" title="' . $title . '" id="popup-accept" class="button">' . $title . '</a>';
    // Turn the Cancel Link Title field into an anchor tag.
    $var['content']['field_cancel_link_title'][0]['#markup'] = '<a href="#" id="popup-reject" class="button" title="' . t('I do not want to participate in the survey.') . '">' . $reject . '</a>';
    // Turn the title field into an H2 tag.
    $var['content']['title_field'][0]['#markup'] = '<h2>' . $var['content']['title_field'][0]['#markup'] . '</h2>';
    // Add the message class to the bean's container.
    unset($var['content']['field_survey_link_title']);
    // DEBUG: dpm($var);
  }
}
