popup_survey.popup_survey.*:
  type: config_entity
  label: 'PopupSurvey config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    cancel_link_title:
      type: text
      label: 'Cancel Link Title'
    popup_body:
      type: text
      label: 'Popup Body'
    survey_link:
      type: text
      label: 'Survey Link'
    survey_link_title:
      type: text
      label: 'Survey Link Title'
